export interface LanguageItem {
  id: string;
  name: string;
  code: string;
  dir?: 'ltr' | 'rtl';
}

export const LANGUAGES: LanguageItem[] = [
  { id: 'en', name: 'English', code: 'EN', dir: 'ltr' },
  { id: 'ar', name: 'العربية', code: 'AR', dir: 'rtl' },
  { id: 'zh', name: '简体中文', code: 'ZH', dir: 'ltr' },
  { id: 'ja', name: '日本語', code: 'JA', dir: 'ltr' },
  { id: 'ru', name: 'Русский', code: 'RU', dir: 'ltr' },
  { id: 'fr', name: 'Français', code: 'FR', dir: 'ltr' },
  { id: 'de', name: 'Deutsch', code: 'DE', dir: 'ltr' },
  { id: 'es', name: 'Español', code: 'ES', dir: 'ltr' },
];

export type LanguageCode = 'en' | 'ar' | 'zh' | 'ja' | 'ru' | 'fr' | 'de' | 'es';

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    // Navigation & Tabs
    home: 'Overview',
    chat: 'Workspace Chat',
    jobs: 'Cron & Tasks',
    settings: 'Ops & Settings',
    inference: 'Inference',
    daemonOps: 'Daemon & Ops',
    preferences: 'Preferences',
    skillsMemory: 'Skills & Memory',

    // Themes
    themeTitle: 'Theme & Palette',
    themeSubtitle: 'Desktop palettes only. The selected mode is applied on top.',
    searchThemes: 'Search your themes or the VS Code Marketplace...',
    light: 'Light',
    dark: 'Dark',
    system: 'System',

    // Languages
    languageTitle: 'Language & Locale',
    languageSubtitle: 'Select your interface language. Hermes will adapt text, labels, and text direction.',
    searchLanguages: 'Search languages...',

    // Header & Status
    connected: 'Connected',
    offline: 'Offline',
    starting: 'Starting',
    approvalNeeded: 'Approval',
    inspector: 'Inspector',
    deskTag: 'DESK',
    newSession: 'New Session',
    filterSessions: 'Filter sessions...',
    search: 'Search',
    quickLanguage: 'Language',

    // Agent States
    agentStatusOnline: 'Active & Listening',
    agentStatusThinking: 'Deliberating',
    agentStatusExecuting: 'Executing Tools',
    agentStatusWaiting: 'Action Required',
    agentStatusConnecting: 'Connecting Daemon',
    agentStatusOffline: 'Daemon Offline',
    agentStatusError: 'Agent Error',
    agentStatusOnlineDesc: 'Ready to process commands, tools, and background requests',
    agentStatusThinkingDesc: 'Formulating step-by-step reasoning and plan of action',
    agentStatusExecutingDesc: 'Running tool invocations and streaming generated payload',

    // Home Overview
    daemonSupervised: 'Daemon Supervised',
    gatewayStatus: 'Gateway Status',
    activeModel: 'Active Model',
    quickActions: 'Quick Actions',
    launchChat: 'Launch New Workspace Chat',
    launchChatDesc: 'Open an interactive session with full tool autonomy',
    diagnosticsAction: 'Verify Gateway Diagnostics',
    diagnosticsActionDesc: 'Check local IPC bridge, node environment, and health',
    cronAction: 'Inspect Scheduled Background Cron',
    cronActionDesc: 'Manage periodic tasks, heartbeat timers, and triggers',
    settingsAction: 'Customize Providers & Appearance',
    settingsActionDesc: 'Change theme palette, active LLM endpoints, and security',
    recentSessions: 'Recent Sessions',
    scheduledCron: 'Scheduled Background Jobs',
    noSessionsYet: 'No active sessions yet',
    noJobsYet: 'No cron jobs scheduled',

    // Providers & Settings
    configuredProviders: 'Configured Model Providers',
    addProvider: '+ Add Provider',
    editProvider: 'Edit Provider',
    active: 'Active',
    use: 'Use',
    edit: 'Edit',
    delete: 'Delete',
    apiKey: 'API Key',
    baseUrl: 'Base URL Endpoint',
    defaultModel: 'Default Model Identifier',
    testKey: 'Test Key',
    testingKey: 'Testing...',
    keyValid: 'Key is valid & responding',
    keyInvalid: 'Failed to authenticate',
    modelCatalog: 'Provider Type',
    helpToday: 'How can Hermes help today?',
    formulating: 'Formulating response...',
    noModel: 'No model',
    selectProvider: 'Select a provider...',
    providerRequired: 'Choose a provider first.',
    noModelsMatch: 'No models match your search.',
    noModelsProvider: 'No models found for this provider.',
    approvalTitle: 'Security Approval Required',
    pending: 'pending',
    deny: 'Deny',
    allowOnce: 'Allow Once',
    allowSession: 'Allow Session',
    queuedFor: 'for execution',
    nextRun: 'Next execution',
    speechUnsupported: 'Speech recognition is not supported in this browser.',
    copyFailed: 'Copy failed: clipboard unavailable',

    // Preferences & Controls
    fontScale: 'Chat Font Scale',
    fontScaleDesc: 'Adjust the reading scale of conversation messages and code blocks',
    reasoningEffort: 'Default Reasoning Effort',
    reasoningEffortDesc: 'Budget allocated for deliberate chain-of-thought before response',
    effortLow: 'Low',
    effortMedium: 'Medium',
    effortHigh: 'High',
    autoApprove: 'Auto-Approve Tool Actions',
    autoApproveDesc: 'Bypass manual approval confirmations for shell and file writes',
    appLock: '4-Digit App Lock PIN',
    appLockDesc: 'Require PIN unlock before displaying conversations or settings',
    telegramBridge: 'Telegram Bot Bridge',
    telegramBridgeDesc: 'Remote webhook token for mobile chat relay',
    save: 'Save Changes',
    cancel: 'Cancel',
    clearLogs: 'Clear Logs',
    restartDaemon: 'Restart Daemon',
    saveKeys: 'Save Credentials',

    // Chat Screen
    askHermes: 'Message Hermes or paste instructions...',
    send: 'Send',
    stop: 'Stop Execution',
    thinkingProcess: 'Thinking Process',
    toolCalls: 'Tool Execution',
    emptyChatTitle: 'Hermes Workspace Agent',
    emptyChatDesc: 'Autonomous reasoning, terminal tool execution, and local orchestration ready.',
    selectModel: 'Select Model',
    searchModels: 'Filter models or custom paths...',
    clearChat: 'Clear History',
    copy: 'Copy',
    fork: 'Fork Session',
    exportChat: 'Export Markdown',
    approve: 'Approve & Execute',
    reject: 'Reject',

    // Jobs Screen
    scheduledJobsTitle: 'Scheduled Cron Jobs',
    scheduledJobsDesc: 'Autonomous agent wake-ups scheduled with cron intervals',
    newJob: '+ New Cron Job',
    jobName: 'Job Name',
    cronSchedule: 'Cron Schedule (e.g. 0 9 * * *)',
    instructions: 'Agent Prompt Instructions',
    enabled: 'Enabled',
    actions: 'Actions',
    runNow: 'Run Now',
    runsHistory: 'Execution History',
    lastRun: 'Last Run',

    // Settings: providers
    providersDesc: 'Connect multiple LLM providers simultaneously (DeepSeek, OpenAI, Anthropic, Gemini, Ollama, etc.) and switch between them on the fly.',
    noProviders: 'No providers configured. Add one to start chatting.',
    defaultModelShort: 'Default Model',
    customProxy: 'Custom Proxy',
    officialEndpoint: 'Official Endpoint',
    switchedTo: 'Active provider switched to',
    removedItem: 'Removed',
    updatedItem: 'Updated',
    addedActivated: 'Added and activated',
    keyPattern: 'Key pattern verified',
    skillEnabled: 'Skill enabled',
    skillDisabled: 'Skill disabled',
    blueprintLaunched: 'Workflow routine launched into active session',
    appliedPrefix: 'Applied',
    themeWord: 'theme',

    // Settings: gateway daemon
    gatewaySupervisor: 'Gateway Daemon Supervisor',
    stateLabel: 'State',
    running: 'Running',
    stopped: 'Stopped',
    gatewayStarted: 'Gateway service started',
    gatewayStopped: 'Gateway service stopped',
    startDaemon: 'Start Daemon',
    stopShort: 'Stop',
    autostartTitle: 'Auto-launch on startup',
    autostartDesc: 'Initialize local gateway automatically upon opening app',
    autostartEnabled: 'Auto-start enabled',
    autostartDisabled: 'Auto-start disabled',
    diagnosticsTitle: 'System Diagnostics',
    diagnosticsDesc: 'Comprehensive audit of local execution components',
    auditing: 'Auditing…',
    runDiagnostics: 'Run Diagnostics',
    snapshotTitle: 'Local Snapshot',
    snapshotDesc: 'Save workspace sessions, cron schedules, and settings.',
    backingUp: 'Backing up…',
    createSnapshot: 'Create Snapshot',
    debugTitle: 'Debug Bundle',
    debugDesc: 'Extract sanitized socket connection logs and daemon traces.',
    exporting: 'Exporting…',
    generateBundle: 'Generate Bundle',

    // Settings: interface, security, bridges
    interfaceSecurityTitle: 'Interface & Security Controls',
    interfaceSecurityDesc: 'Customize chat scale, automated security grants, and local lockouts.',
    effortNone: 'None',
    disabled: 'Disabled',
    locked: 'Locked',
    changePin: 'Change PIN',
    newPinPlaceholder: 'New PIN (4-8 digits)',
    confirmPinPlaceholder: 'Confirm PIN',
    pinMismatch: 'PINs do not match.',
    pinLength: 'PIN must be 4 to 8 digits.',
    pinCommon: 'That PIN is too common. Choose a different one.',
    pinRepeated: 'Repeated-digit PINs are not allowed. Choose a different one.',
    saveNewPin: 'Save New PIN',
    setPinEnable: 'Set PIN & Enable Lock',
    discordBridge: 'Discord Bot Bridge',
    discordBridgeDesc: 'Optional bridge to chat with Hermes via Discord',
    botTokenPlaceholder: 'Bot token...',
    tgSaved: 'Telegram bot token saved',
    discordSaved: 'Discord bot token saved',
    serverKeyTitle: 'Gateway Server Key',
    serverKeyDesc: 'Auth key the app uses to talk to the local gateway daemon',
    serverKeyPlaceholder: 'Server key...',
    serverKeySaved: 'Gateway server key saved',
    saveShort: 'Save',

    // Settings: library
    skillsCatalog: 'Agent Skills Catalog',
    skillsCatalogDesc: 'Modular tool plugins available to the prompt context',
    refresh: 'Refresh',
    memoryTitle: 'Persistent Semantic Memory',
    memoryEmpty: 'Long term semantic vectors active across sessions.',
    providerLabel: 'Provider',
    entriesLabel: 'Entries',
    localVector: 'local-vector',
    blueprintsTitle: 'Blueprint Automation Workflows',
    launch: 'Launch',
    launchRoutine: 'Launch Routine',
    editModelProvider: 'Edit Model Provider',
    addModelProvider: 'Add Model Provider',
    profileLabel: 'Profile Label',
    profilePlaceholder: 'e.g. My Anthropic Key / DeepSeek Work',
    optionalLocal: '(optional for local providers)',
    optionalSuffix: '(optional)',
    modelLabel: 'Model',
    autostartWizardDesc: 'With this enabled, the gateway initializes automatically when the app loads.',
    keyRequired: 'An API key is required for this provider (LM Studio and Ollama Cloud work without one).',
    unknownProviderUrl: 'This provider id is not recognized: a Base URL endpoint is required.',
    customProviderRequired: 'Enter a custom provider id.',
    customUrlRequired: 'Custom providers need a Base URL endpoint.',
    saveEnable: 'Save & Enable',

    // Onboarding wizard
    stepWord: 'Step',
    ofWord: 'of',
    stepWelcome: 'Welcome',
    stepEnvironment: 'Environment',
    stepCredentials: 'API Credentials',
    stepStart: 'Start Daemon',
    welcomeTitle: 'Welcome to Hermes Mobile',
    welcomeDesc: 'Hermes Mobile gives you a native on-device gateway experience with streaming tool executions, reasoning accordions, autonomous scheduled cron jobs, and multi-model access.',
    zeroTelemetry: 'Zero-Cloud Telemetry',
    zeroTelemetryDesc: 'Your keys, chat histories, and cron triggers stay strictly on your device.',
    continue: 'Continue',
    preparingEnv: 'Preparing Gateway Environment',
    installingMsg: 'Unpacking runtime layers and configuring daemon sockets…',
    installedMsg: 'Environment verified and ready.',
    failedMsg: 'An error occurred during verification.',
    continueCredentials: 'Continue to Credentials',
    retrySetup: 'Retry Setup',
    back: 'Back',
    modelCredentials: 'Model Credentials',
    modelCredentialsDesc: 'Select your preferred LLM provider and enter your API key.',
    customOn: 'Custom: On',
    customOff: 'Custom: Off',
    saveContinue: 'Save and Continue',
    launchGateway: 'Launch On-Device Gateway',
    launchGatewayDesc: 'Start the local socket daemon to begin processing conversations.',
    enable: 'Enable',
    skip: 'Skip',
    launchHermes: 'Launch Hermes',
    skipWorkspace: 'Skip to Workspace',

    // App lock gate
    tooManyAttempts: 'Too many wrong attempts. Try again in',
    incorrectPin: 'Incorrect PIN.',
    attemptsLeft: 'attempts left',
    lockedTitle: 'Workspace Locked',
    enterPin: 'Enter your',
    digitPinAccess: '-digit PIN to access Hermes Mobile',
    clear: 'Clear',
    deleteLabel: 'Delete',
    lockedFor: 'Locked for',
    pinLocalOnly: 'PIN is stored only on this device',
    digitLabel: 'Digit',

    // Relative time (homeAgo)
    timeJustNow: 'Just now',
    timeMinAgo: '{n} min ago',
    timeHourAgo: '{n} hr ago',
    timeDayAgo: '{n} days ago',
    timeNever: 'Never',
  },

  ar: {
    // Navigation & Tabs
    home: 'نظرة عامة',
    chat: 'مساحة المحادثة',
    jobs: 'المهام المجدولة',
    settings: 'العمليات والإعدادات',
    inference: 'الاستدلال والمزودات',
    daemonOps: 'الخدمة والعمليات',
    preferences: 'التفضيلات والمظهر',
    skillsMemory: 'المهارات والذاكرة',

    // Themes
    themeTitle: 'السمة والمظهر',
    themeSubtitle: 'لوحات سطح المكتب فقط. يتم تطبيق الوضع المختار (فاتح/داكن) فوقها.',
    searchThemes: 'ابحث في السمات أو متجر VS Code...',
    light: 'فاتح',
    dark: 'داكن',
    system: 'النظام',

    // Languages
    languageTitle: 'اللغة والمنطقة',
    languageSubtitle: 'اختر لغة الواجهة. سيتكيف هيرمس مع النصوص والاتجاهات والعناوين.',
    searchLanguages: 'البحث عن اللغات...',

    // Header & Status
    connected: 'متصل',
    offline: 'غير متصل',
    starting: 'جارٍ البدء',
    approvalNeeded: 'موافقة مطلوبة',
    inspector: 'المفتش',
    deskTag: 'مكتبي',
    newSession: 'جلسة جديدة',
    filterSessions: 'تصفية الجلسات...',
    search: 'بحث',
    quickLanguage: 'اللغة',

    // Agent States
    agentStatusOnline: 'نشط وجاهز للعمل',
    agentStatusThinking: 'جارٍ التفكير المنطقي',
    agentStatusExecuting: 'جارٍ تنفيذ الأدوات',
    agentStatusWaiting: 'إجراء يتطلب الموافقة',
    agentStatusConnecting: 'جارٍ الاتصال بالخدمة',
    agentStatusOffline: 'الخدمة غير متصلة',
    agentStatusError: 'خطأ في الوكيل',
    agentStatusOnlineDesc: 'جاهز لمعالجة الأوامر واستدعاء الأدوات والمهام الخلفية',
    agentStatusThinkingDesc: 'صياغة التفكير المنطقي خطوة بخطوة وتحديد خطة العمل',
    agentStatusExecutingDesc: 'تشغيل أوامر الأدوات ودفق المخرجات المستلمة',

    // Home Overview
    daemonSupervised: 'الخدمة تحت المراقبة',
    gatewayStatus: 'حالة البوابة',
    activeModel: 'النموذج النشط',
    quickActions: 'الإجراءات السريعة',
    launchChat: 'بدء جلسة عمل جديدة',
    launchChatDesc: 'فتح محادثة تفاعلية مع استقلالية تامة في استخدام الأدوات',
    diagnosticsAction: 'فحص تشخيصات البوابة',
    diagnosticsActionDesc: 'التحقق من جسر IPC المحلي وبيئة العمل وصحة النظام',
    cronAction: 'فحص المهام المجدولة بالخلفية',
    cronActionDesc: 'إدارة المهام الدورية ومؤقتات النبض ومحفزات التشغيل',
    settingsAction: 'تخصيص المزودات والمظهر',
    settingsActionDesc: 'تغيير لوحة الألوان ومزودات الذكاء الاصطناعي والأمان',
    recentSessions: 'الجلسات الأخيرة',
    scheduledCron: 'المهام المجدولة بالخلفية',
    noSessionsYet: 'لا توجد جلسات نشطة بعد',
    noJobsYet: 'لا توجد مهام مجدولة حالياً',

    // Providers & Settings
    configuredProviders: 'مزودو النماذج المضافة',
    addProvider: '+ إضافة مزود',
    editProvider: 'تعديل المزود',
    active: 'نشط',
    use: 'استخدام',
    edit: 'تعديل',
    delete: 'حذف',
    apiKey: 'مفتاح API',
    baseUrl: 'رابط الخادم (Base URL)',
    defaultModel: 'النموذج الافتراضي',
    testKey: 'اختبار المفتاح',
    testingKey: 'جارٍ الاختبار...',
    keyValid: 'المفتاح صالح ويعمل بنجاح',
    keyInvalid: 'فشل التحقق من المفتاح',
    modelCatalog: 'نوع المزود',
    helpToday: 'كيف يمكن أن يساعدك Hermes اليوم؟',
    formulating: 'جارٍ صياغة الرد...',
    noModel: 'لا يوجد نموذج',
    selectProvider: 'اختر مزودا...',
    providerRequired: 'اختر المزود اولا.',
    noModelsMatch: 'لا توجد نماذج تطابق بحثك.',
    noModelsProvider: 'لا توجد نماذج لهذا المزود.',
    approvalTitle: 'مطلوب موافقة أمنية',
    pending: 'معلقة',
    deny: 'رفض',
    allowOnce: 'سماح مرة واحدة',
    allowSession: 'سماح للجلسة',
    queuedFor: 'للتنفيذ',
    nextRun: 'التنفيذ التالي',
    speechUnsupported: 'التعرف على الصوت غير مدعوم في هذا المتصفح.',
    copyFailed: 'فشل النسخ: الحافظة غير متاحة',

    // Preferences & Controls
    fontScale: 'حجم خط المحادثة',
    fontScaleDesc: 'تعديل حجم قراءة رسائل المحادثة وكتل الشيفرة البرمجية',
    reasoningEffort: 'مستوى التفكير المنطقي',
    reasoningEffortDesc: 'الوقت والجهد المخصص للتفكير المتسلسل قبل الإجابة',
    effortLow: 'منخفض',
    effortMedium: 'متوسط',
    effortHigh: 'مكثف',
    autoApprove: 'الموافقة التلقائية على الأدوات',
    autoApproveDesc: 'تجاوز طلب التأكيد اليدوي لتنفيذ أوامر الطرفية وتعديل الملفات',
    appLock: 'قفل التطبيق برمز PIN',
    appLockDesc: 'طلب إدخال رمز المرور قبل فتح المحادثات أو الإعدادات',
    telegramBridge: 'جسر بوت تليجرام',
    telegramBridgeDesc: 'رمز الويب هوك للتحكم عن بُعد بالمحادثة عبر الهاتف',
    save: 'حفظ التغييرات',
    cancel: 'إلغاء',
    clearLogs: 'مسح السجلات',
    restartDaemon: 'إعادة تشغيل الخدمة',
    saveKeys: 'حفظ بيانات الاعتماد',

    // Chat Screen
    askHermes: 'أرسل رسالة إلى هيرمس أو الصق التعليمات...',
    send: 'إرسال',
    stop: 'إيقاف التنفيذ',
    thinkingProcess: 'سلسلة التفكير المنطقي',
    toolCalls: 'تنفيذ الأدوات والطرفية',
    emptyChatTitle: 'مساعد هيرمس المستقل',
    emptyChatDesc: 'تفكير ذاتي، تنفيذ أدوات الطرفية، وتنسيق المهام البرمجية محلياً.',
    selectModel: 'اختيار النموذج',
    searchModels: 'تصفية النماذج أو المسارات المخصصة...',
    clearChat: 'مسح السجل',
    copy: 'نسخ',
    fork: 'تفريغ الجلسة',
    exportChat: 'تصدير كملف Markdown',
    approve: 'موافقة وتنفيذ',
    reject: 'رفض',

    // Jobs Screen
    scheduledJobsTitle: 'المهام المجدولة (Cron)',
    scheduledJobsDesc: 'استيقاظ تلقائي للوكيل في أوقات مجدولة بشكل دوري',
    newJob: '+ مهمة مجدولة جديدة',
    jobName: 'اسم المهمة',
    cronSchedule: 'توقيت Cron (مثال: 0 9 * * *)',
    instructions: 'تعليمات الوكيل البرمجية',
    enabled: 'مفعل',
    actions: 'الإجراءات',
    runNow: 'تشغيل الآن',
    runsHistory: 'سجل عمليات التشغيل',
    lastRun: 'آخر تشغيل',

    // Settings: providers
    providersDesc: 'قم بتوصيل عدة مزودات نماذج لغوية في نفس الوقت (DeepSeek وOpenAI وAnthropic وGemini وOllama وغيرها) والتبديل بينها مباشرة.',
    noProviders: 'لا توجد مزودات مضافة. أضف واحداً لبدء المحادثة.',
    defaultModelShort: 'النموذج الافتراضي',
    customProxy: 'وكيل مخصص',
    officialEndpoint: 'النقطة الرسمية',
    switchedTo: 'تم التبديل إلى المزود النشط:',
    removedItem: 'تمت إزالة',
    updatedItem: 'تم تحديث',
    addedActivated: 'تمت الإضافة والتفعيل:',
    keyPattern: 'تم التحقق من نمط المفتاح',
    skillEnabled: 'تم تفعيل المهارة',
    skillDisabled: 'تم تعطيل المهارة',
    blueprintLaunched: 'تم إطلاق سير العمل في الجلسة النشطة',
    appliedPrefix: 'تم تطبيق',
    themeWord: 'السمة',

    // Settings: gateway daemon
    gatewaySupervisor: 'مشرف خدمة البوابة',
    stateLabel: 'الحالة',
    running: 'يعمل',
    stopped: 'متوقف',
    gatewayStarted: 'بدأت خدمة البوابة',
    gatewayStopped: 'توقفت خدمة البوابة',
    startDaemon: 'تشغيل الخدمة',
    stopShort: 'إيقاف',
    autostartTitle: 'التشغيل التلقائي عند البدء',
    autostartDesc: 'تهيئة البوابة المحلية تلقائياً عند فتح التطبيق',
    autostartEnabled: 'تم تفعيل التشغيل التلقائي',
    autostartDisabled: 'تم تعطيل التشغيل التلقائي',
    diagnosticsTitle: 'تشخيصات النظام',
    diagnosticsDesc: 'تدقيق شامل لمكونات التنفيذ المحلية',
    auditing: 'جارٍ الفحص…',
    runDiagnostics: 'تشغيل التشخيصات',
    snapshotTitle: 'نسخة محلية',
    snapshotDesc: 'حفظ جلسات مساحة العمل وجداول cron والإعدادات.',
    backingUp: 'جارٍ النسخ…',
    createSnapshot: 'إنشاء نسخة',
    debugTitle: 'حزمة التصحيح',
    debugDesc: 'استخراج سجلات الاتصال وآثار الخدمة بعد التنقية.',
    exporting: 'جارٍ التصدير…',
    generateBundle: 'إنشاء الحزمة',

    // Settings: interface, security, bridges
    interfaceSecurityTitle: 'التحكم في الواجهة والأمان',
    interfaceSecurityDesc: 'تخصيص حجم المحادثة والمنح الأمنية التلقائية والأقفال المحلية.',
    effortNone: 'بلا',
    disabled: 'معطل',
    locked: 'مقفل',
    changePin: 'تغيير رمز PIN',
    newPinPlaceholder: 'رمز PIN جديد (4-8 أرقام)',
    confirmPinPlaceholder: 'تأكيد رمز PIN',
    pinMismatch: 'رمزا PIN غير متطابقين.',
    pinLength: 'يجب أن يتكون رمز PIN من 4 إلى 8 أرقام.',
    pinCommon: 'هذا الرمز شائع جداً. اختر رمزاً آخر.',
    pinRepeated: 'الرموز ذات الأرقام المكررة غير مسموحة. اختر رمزاً آخر.',
    saveNewPin: 'حفظ الرمز الجديد',
    setPinEnable: 'تعيين الرمز وتفعيل القفل',
    discordBridge: 'جسر بوت ديسكورد',
    discordBridgeDesc: 'جسر اختياري للمحادثة مع هيرمس عبر ديسكورد',
    botTokenPlaceholder: 'رمز البوت...',
    tgSaved: 'تم حفظ رمز بوت تليجرام',
    discordSaved: 'تم حفظ رمز بوت ديسكورد',
    serverKeyTitle: 'مفتاح خادم البوابة',
    serverKeyDesc: 'مفتاح المصادقة الذي يستخدمه التطبيق للتحدث مع خدمة البوابة',
    serverKeyPlaceholder: 'مفتاح الخادم...',
    serverKeySaved: 'تم حفظ مفتاح الخادم',
    saveShort: 'حفظ',

    // Settings: library
    skillsCatalog: 'كتالوج مهارات الوكيل',
    skillsCatalogDesc: 'إضافات أدوات نمطية متاحة ضمن سياق الطلب',
    refresh: 'تحديث',
    memoryTitle: 'الذاكرة الدلالية الدائمة',
    memoryEmpty: 'متجهات دلالية طويلة الأمد نشطة عبر الجلسات.',
    providerLabel: 'المزود',
    entriesLabel: 'المدخلات',
    localVector: 'local-vector',
    blueprintsTitle: 'سير عمل الأتمتة (Blueprints)',
    launch: 'تشغيل',
    launchRoutine: 'تشغيل الروتين',
    editModelProvider: 'تعديل مزود النموذج',
    addModelProvider: 'إضافة مزود نموذج',
    profileLabel: 'تسمية الملف',
    profilePlaceholder: 'مثال: مفتاح Anthropic الخاص / عمل DeepSeek',
    optionalLocal: '(اختياري للمزودات المحلية)',
    optionalSuffix: '(اختياري)',
    modelLabel: 'النموذج',
    autostartWizardDesc: 'عند تفعيل هذا الخيار، تُهيَّأ البوابة تلقائياً عند فتح التطبيق.',
    keyRequired: 'مفتاح API مطلوب لهذا المزود (يعمل LM Studio وOllama Cloud بدونه).',
    unknownProviderUrl: 'معرف المزود غير معروف: يلزم إدخال رابط Base URL.',
    customProviderRequired: 'أدخل معرف مزود مخصص.',
    customUrlRequired: 'المزودات المخصصة تحتاج رابط Base URL.',
    saveEnable: 'حفظ وتفعيل',

    // Onboarding wizard
    stepWord: 'خطوة',
    ofWord: 'من',
    stepWelcome: 'مرحباً',
    stepEnvironment: 'البيئة',
    stepCredentials: 'بيانات API',
    stepStart: 'تشغيل الخدمة',
    welcomeTitle: 'مرحباً بك في هيرمس موبايل',
    welcomeDesc: 'يمنحك هيرمس موبايل تجربة بوابة أصلية على الجهاز مع تنفيذ الأدوات بالبث المباشر وترتيبات الاستدلال ومهام cron المجدولة ذاتية التشغيل والوصول متعدد النماذج.',
    zeroTelemetry: 'خصوصية تامة بلا سحابة',
    zeroTelemetryDesc: 'مفاتيحك وسجلات محادثاتك ومحفزات cron تبقى على جهازك فقط.',
    continue: 'متابعة',
    preparingEnv: 'تجهيز بيئة البوابة',
    installingMsg: 'جارٍ فك طبقات التشغيل وضبط مقابس الخدمة…',
    installedMsg: 'تم التحقق من البيئة وهي جاهزة.',
    failedMsg: 'حدث خطأ أثناء التحقق.',
    continueCredentials: 'المتابعة إلى بيانات الاعتماد',
    retrySetup: 'إعادة المحاولة',
    back: 'رجوع',
    modelCredentials: 'بيانات اعتماد النموذج',
    modelCredentialsDesc: 'اختر مزود النماذج المفضل وأدخل مفتاح API.',
    customOn: 'مخصص: مفعّل',
    customOff: 'مخصص: معطّل',
    saveContinue: 'حفظ ومتابعة',
    launchGateway: 'تشغيل بوابة الجهاز',
    launchGatewayDesc: 'ابدأ خدمة المقبس المحلية لبدء معالجة المحادثات.',
    enable: 'تفعيل',
    skip: 'تخطي',
    launchHermes: 'تشغيل هيرمس',
    skipWorkspace: 'تخطي إلى مساحة العمل',

    // App lock gate
    tooManyAttempts: 'محاولات خاطئة كثيرة. حاول مجدداً بعد',
    incorrectPin: 'رمز PIN غير صحيح.',
    attemptsLeft: 'محاولات متبقية',
    lockedTitle: 'مساحة العمل مقفلة',
    enterPin: 'أدخل رمز PIN المكون من',
    digitPinAccess: 'أرقام للوصول إلى هيرمس موبايل',
    clear: 'مسح',
    deleteLabel: 'حذف',
    lockedFor: 'مقفل لمدة',
    pinLocalOnly: 'يُحفظ رمز PIN على هذا الجهاز فقط',
    digitLabel: 'رقم',

    // Relative time (homeAgo)
    timeJustNow: 'الآن',
    timeMinAgo: 'قبل {n} دقيقة',
    timeHourAgo: 'قبل {n} ساعة',
    timeDayAgo: 'قبل {n} يوم',
    timeNever: 'أبداً',
  },

  zh: {
    home: '概览',
    chat: '工作区对话',
    jobs: '定时任务',
    settings: '运维与设置',
    inference: '推理端点',
    daemonOps: '守护进程与运维',
    preferences: '偏好设置与外观',
    skillsMemory: '技能与记忆',
    themeTitle: '主题与调色板',
    themeSubtitle: '仅限桌面调色板。所选模式将覆盖其上。',
    searchThemes: '搜索主题或 VS Code 市场...',
    light: '浅色',
    dark: '深色',
    system: '系统',
    languageTitle: '语言与区域',
    languageSubtitle: '选择界面语言。Hermes 将自适应文本、标签和排版方向。',
    searchLanguages: '搜索语言...',
    connected: '已连接',
    offline: '离线',
    starting: '启动中',
    approvalNeeded: '待审批',
    inspector: '审查器',
    deskTag: '桌面',
    newSession: '新建会话',
    filterSessions: '过滤会话...',
    search: '搜索',
    quickLanguage: '语言',
    agentStatusOnline: '活跃并监听中',
    agentStatusThinking: '正在推理中',
    agentStatusExecuting: '正在执行工具',
    agentStatusWaiting: '等待批准',
    agentStatusConnecting: '正在连接守护进程',
    agentStatusOffline: '守护进程已离线',
    agentStatusError: '智能体错误',
    agentStatusOnlineDesc: '准备处理指令、工具和后台请求',
    agentStatusThinkingDesc: '正在逐步构思逻辑与行动计划',
    agentStatusExecutingDesc: '正在运行工具调用并流式传输生成结果',
    daemonSupervised: '守护进程已托管',
    gatewayStatus: '网关状态',
    activeModel: '当前模型',
    quickActions: '快捷操作',
    launchChat: '开启新工作区对话',
    launchChatDesc: '打开具备完整工具自主权的交互式会话',
    diagnosticsAction: '验证网关诊断信息',
    diagnosticsActionDesc: '检查本地 IPC 桥接、运行环境及健康状况',
    cronAction: '检查后台计划定时任务',
    cronActionDesc: '管理周期性任务、心跳定时器及触发器',
    settingsAction: '自定义模型提供商与外观',
    settingsActionDesc: '更改主题调色板、LLM 端点及安全配置',
    recentSessions: '最近会话',
    scheduledCron: '后台定时任务',
    noSessionsYet: '暂无活跃会话',
    noJobsYet: '暂无定时任务',
    configuredProviders: '已配置的模型提供商',
    addProvider: '+ 添加提供商',
    editProvider: '编辑提供商',
    active: '活跃',
    use: '使用',
    edit: '编辑',
    delete: '删除',
    apiKey: 'API 密钥',
    baseUrl: 'Base URL 端点',
    defaultModel: '默认模型标识符',
    testKey: '测试密钥',
    testingKey: '正在测试...',
    keyValid: '密钥有效且响应正常',
    keyInvalid: '认证失败',
    modelCatalog: '提供商类型',
    fontScale: '聊天字体比例',
    fontScaleDesc: '调整对话消息与代码块的阅读缩放比例',
    reasoningEffort: '默认思考强度',
    reasoningEffortDesc: '生成回答前分配的链式思考预算',
    effortLow: '低',
    effortMedium: '中',
    effortHigh: '高',
    autoApprove: '自动批准工具操作',
    autoApproveDesc: '跳过终端命令与文件写入的手动确认提示',
    appLock: '4位数字应用锁 PIN',
    appLockDesc: '在查看会话或设置前必须输入 PIN 码解锁',
    telegramBridge: 'Telegram 机器人网桥',
    telegramBridgeDesc: '用于手机端远程聊天的 Webhook 令牌',
    save: '保存更改',
    cancel: '取消',
    clearLogs: '清空日志',
    restartDaemon: '重启守护进程',
    saveKeys: '保存凭据',
    askHermes: '向 Hermes 发送消息或粘贴指令...',
    send: '发送',
    stop: '停止执行',
    thinkingProcess: '推理链过程',
    toolCalls: '工具执行',
    emptyChatTitle: 'Hermes 工作区智能体',
    emptyChatDesc: '自主推理、终端工具调用与本地编排已就绪。',
    selectModel: '选择模型',
    searchModels: '过滤模型或输入自定义路径...',
    clearChat: '清空历史',
    copy: '复制',
    fork: '分叉会话',
    exportChat: '导出 Markdown',
    approve: '批准并执行',
    reject: '拒绝',
    scheduledJobsTitle: '定时任务 (Cron)',
    scheduledJobsDesc: '基于 Cron 周期的智能体自动唤醒任务',
    newJob: '+ 新建定时任务',
    jobName: '任务名称',
    cronSchedule: 'Cron 表达式 (例如: 0 9 * * *)',
    instructions: '智能体指令内容',
    enabled: '已启用',
    actions: '操作',
    runNow: '立即运行',
    runsHistory: '运行记录',
    lastRun: '上次运行',
  },

  ja: {
    home: '概要',
    chat: 'ワークスペース対話',
    jobs: 'タスク管理',
    settings: '運用と設定',
    inference: '推論エンドポイント',
    daemonOps: 'デーモンと運用',
    preferences: '環境設定と外観',
    skillsMemory: 'スキルとメモリ',
    themeTitle: 'テーマと配色',
    themeSubtitle: 'デスクトップパレットのみ。選択したモードが重ねて適用されます。',
    searchThemes: 'テーマまたは VS Code マーケットプレイスを検索...',
    light: 'ライト',
    dark: 'ダーク',
    system: 'システム',
    languageTitle: '言語と地域',
    languageSubtitle: 'インターフェース言語を選択します。テキスト、ラベル、文字方向が適応されます。',
    searchLanguages: '言語を検索...',
    connected: '接続中',
    offline: 'オフライン',
    starting: '起動中',
    approvalNeeded: '承認待ち',
    inspector: 'インスペクタ',
    deskTag: 'デスクトップ',
    newSession: '新規セッション',
    filterSessions: 'セッションを検索...',
    search: '検索',
    quickLanguage: '言語',
    agentStatusOnline: 'アクティブ・待機中',
    agentStatusThinking: '思考・推論中',
    agentStatusExecuting: 'ツール実行中',
    agentStatusWaiting: '承認待ちアクション',
    agentStatusConnecting: 'デーモンに接続中',
    agentStatusOffline: 'デーモン停止中',
    agentStatusError: 'エージェントエラー',
    agentStatusOnlineDesc: 'コマンド、ツール、バックグラウンド処理の受付準備完了',
    agentStatusThinkingDesc: '段階的な論理思考と実行プランを策定中',
    agentStatusExecutingDesc: 'ツール呼び出しを実行しストリーミング中',
    daemonSupervised: 'デーモン監視中',
    gatewayStatus: 'ゲートウェイ状態',
    activeModel: 'アクティブモデル',
    quickActions: 'クイックアクション',
    launchChat: '新規対話セッションを開始',
    launchChatDesc: '完全な自律ツール権限を備えた対話を開く',
    diagnosticsAction: '診断情報の確認',
    diagnosticsActionDesc: 'ローカル IPC ブリッジと実行環境の健全性をチェック',
    cronAction: '定期実行タスクの検査',
    cronActionDesc: '定時処理、ハートビート、トリガーを管理',
    settingsAction: 'プロバイダと外観のカスタマイズ',
    settingsActionDesc: 'テーマパレット、モデル、セキュリティ設定を変更',
    recentSessions: '最近のセッション',
    scheduledCron: 'バックグラウンド定期タスク',
    noSessionsYet: 'アクティブなセッションがありません',
    noJobsYet: '定期タスクがありません',
    configuredProviders: '設定済みモデルプロバイダ',
    addProvider: '+ プロバイダ追加',
    editProvider: 'プロバイダ編集',
    active: 'アクティブ',
    use: '適用',
    edit: '編集',
    delete: '削除',
    apiKey: 'API キー',
    baseUrl: 'ベース URL',
    defaultModel: 'デフォルトモデル識別子',
    testKey: 'キーをテスト',
    testingKey: 'テスト中...',
    keyValid: 'キー認証に成功しました',
    keyInvalid: 'キー認証に失敗しました',
    modelCatalog: 'プロバイダタイプ',
    fontScale: 'チャット文字サイズ',
    fontScaleDesc: 'メッセージとコードブロックの表示倍率を調整',
    reasoningEffort: '推論思考レベル',
    reasoningEffortDesc: '応答前の思考チェーンに割り当てるリソース量',
    effortLow: '低',
    effortMedium: '中',
    effortHigh: '高',
    autoApprove: 'ツールアクションの自動承認',
    autoApproveDesc: 'ターミナルコマンドとファイル編集の確認をスキップ',
    appLock: '4桁の PIN ロック',
    appLockDesc: 'チャットや設定を開く前に暗証番号を要求',
    telegramBridge: 'Telegram ボットブリッジ',
    telegramBridgeDesc: 'スマホからのリモート操作用 Webhook トークン',
    save: '変更を保存',
    cancel: 'キャンセル',
    clearLogs: 'ログをクリア',
    restartDaemon: 'デーモン再起動',
    saveKeys: '認証情報を保存',
    askHermes: 'Hermes に指示を入力またはメッセージを送信...',
    send: '送信',
    stop: '実行停止',
    thinkingProcess: '思考プロセス',
    toolCalls: 'ツール実行',
    emptyChatTitle: 'Hermes ワークスペースエージェント',
    emptyChatDesc: '自律推論、ターミナルツールの実行、ローカルオーケストレーション。',
    selectModel: 'モデルを選択',
    searchModels: 'モデルまたはカスタムパスを検索...',
    clearChat: '履歴をクリア',
    copy: 'コピー',
    fork: 'セッションを分岐',
    exportChat: 'Markdown 出力',
    approve: '承認して実行',
    reject: '拒絶',
    scheduledJobsTitle: '定期タスク (Cron)',
    scheduledJobsDesc: 'Cron スケジュールによるエージェントの自律起動',
    newJob: '+ 新規定期タスク',
    jobName: 'タスク名',
    cronSchedule: 'Cron 周期 (例: 0 9 * * *)',
    instructions: '指示プロンプト',
    enabled: '有効',
    actions: '操作',
    runNow: '今すぐ実行',
    runsHistory: '実行履歴',
    lastRun: '最終実行',
  },

  ru: {
    home: 'Обзор',
    chat: 'Рабочий чат',
    jobs: 'Задачи и Cron',
    settings: 'Настройки',
    inference: 'Провайдеры',
    daemonOps: 'Демон и операции',
    preferences: 'Внешний вид',
    skillsMemory: 'Навыки и память',
    themeTitle: 'Тема и палитра',
    themeSubtitle: 'Только настольные палитры. Выбранный режим накладывается сверху.',
    searchThemes: 'Поиск тем...',
    light: 'Светлая',
    dark: 'Тёмная',
    system: 'Системная',
    languageTitle: 'Язык и регион',
    languageSubtitle: 'Выберите язык интерфейса. Hermes адаптирует текст и направление.',
    searchLanguages: 'Поиск языков...',
    connected: 'Подключено',
    offline: 'Отключено',
    starting: 'Запуск',
    approvalNeeded: 'Требуется одобрение',
    inspector: 'Инспектор',
    deskTag: 'НАСТОЛЬНЫЙ',
    newSession: 'Новая сессия',
    filterSessions: 'Фильтр сессий...',
    search: 'Поиск',
    quickLanguage: 'Язык',
    agentStatusOnline: 'Активен и ожидает',
    agentStatusThinking: 'Анализирует задачу',
    agentStatusExecuting: 'Выполняет инструменты',
    agentStatusWaiting: 'Требуется действие',
    agentStatusConnecting: 'Подключение к демону',
    agentStatusOffline: 'Демон остановлен',
    agentStatusError: 'Ошибка агента',
    agentStatusOnlineDesc: 'Готов к выполнению команд и фоновых задач',
    agentStatusThinkingDesc: 'Формулирует логику и пошаговый план действий',
    agentStatusExecutingDesc: 'Запускает инструменты и выводит результаты',
    daemonSupervised: 'Демон под управлением',
    gatewayStatus: 'Статус шлюза',
    activeModel: 'Текущая модель',
    quickActions: 'Быстрые действия',
    launchChat: 'Начать новый диалог',
    launchChatDesc: 'Открыть сессию с полной автономией инструментов',
    diagnosticsAction: 'Диагностика шлюза',
    diagnosticsActionDesc: 'Проверить состояние локального IPC-моста',
    cronAction: 'Фоновые задачи Cron',
    cronActionDesc: 'Управление периодическими задачами и таймерами',
    settingsAction: 'Настройки провайдеров и темы',
    settingsActionDesc: 'Смена палитры, эндпоинтов LLM и безопасности',
    recentSessions: 'Недавние сессии',
    scheduledCron: 'Запланированные задачи',
    noSessionsYet: 'Нет активных сессий',
    noJobsYet: 'Нет запланированных задач',
    configuredProviders: 'Настроенные провайдеры',
    addProvider: '+ Добавить провайдера',
    editProvider: 'Редактировать провайдера',
    active: 'Активен',
    use: 'Выбрать',
    edit: 'Изменить',
    delete: 'Удалить',
    apiKey: 'Ключ API',
    baseUrl: 'Базовый URL',
    defaultModel: 'Модель по умолчанию',
    testKey: 'Проверить ключ',
    testingKey: 'Проверка...',
    keyValid: 'Ключ действителен',
    keyInvalid: 'Ошибка авторизации ключа',
    modelCatalog: 'Тип провайдера',
    fontScale: 'Масштаб шрифта чата',
    fontScaleDesc: 'Размер текста сообщений и блоков кода',
    reasoningEffort: 'Глубина рассуждений',
    reasoningEffortDesc: 'Ресурс, выделяемый на цепочку мыслей перед ответом',
    effortLow: 'Низкая',
    effortMedium: 'Средняя',
    effortHigh: 'Высокая',
    autoApprove: 'Авто-одобрение инструментов',
    autoApproveDesc: 'Пропускать подтверждение терминальных команд и файлов',
    appLock: '4-значный PIN-код',
    appLockDesc: 'Запрашивать PIN-код для входа в приложение',
    telegramBridge: 'Telegram-мост',
    telegramBridgeDesc: 'Токен бота для удаленного чата с телефона',
    save: 'Сохранить',
    cancel: 'Отмена',
    clearLogs: 'Очистить логи',
    restartDaemon: 'Перезапустить демон',
    saveKeys: 'Сохранить ключи',
    askHermes: 'Напишите Hermes или вставьте инструкции...',
    send: 'Отправить',
    stop: 'Остановить',
    thinkingProcess: 'Ход рассуждений',
    toolCalls: 'Вызовы инструментов',
    emptyChatTitle: 'Агент Hermes Workspace',
    emptyChatDesc: 'Автономные рассуждения, вызов системных утилит и локальная оркестрация.',
    selectModel: 'Выбрать модель',
    searchModels: 'Поиск моделей...',
    clearChat: 'Очистить историю',
    copy: 'Копировать',
    fork: 'Ответвить сессию',
    exportChat: 'Экспорт в Markdown',
    approve: 'Одобрить и выполнить',
    reject: 'Отклонить',
    scheduledJobsTitle: 'Задачи по расписанию (Cron)',
    scheduledJobsDesc: 'Периодическое пробуждение агента по интервалам Cron',
    newJob: '+ Новая задача Cron',
    jobName: 'Название задачи',
    cronSchedule: 'Расписание Cron (например, 0 9 * * *)',
    instructions: 'Инструкция для агента',
    enabled: 'Включено',
    actions: 'Действия',
    runNow: 'Запустить сейчас',
    runsHistory: 'История запусков',
    lastRun: 'Последний запуск',
  },

  fr: {
    home: 'Vue d’ensemble',
    chat: 'Chat de travail',
    jobs: 'Tâches Cron',
    settings: 'Paramètres',
    inference: 'Inférence',
    daemonOps: 'Démon & Ops',
    preferences: 'Préférences & Thème',
    skillsMemory: 'Compétences & Mémoire',
    themeTitle: 'Thème & Palette',
    themeSubtitle: 'Palettes de bureau uniquement. Le mode sélectionné s’applique par-dessus.',
    searchThemes: 'Rechercher vos thèmes...',
    light: 'Clair',
    dark: 'Sombre',
    system: 'Système',
    languageTitle: 'Langue & Région',
    languageSubtitle: 'Sélectionnez la langue d’interface. Hermes adapte le texte et la direction.',
    searchLanguages: 'Rechercher des langues...',
    connected: 'Connecté',
    offline: 'Hors ligne',
    starting: 'Démarrage',
    approvalNeeded: 'Approbation requise',
    inspector: 'Inspecteur',
    deskTag: 'BUREAU',
    newSession: 'Nouvelle session',
    filterSessions: 'Filtrer les sessions...',
    search: 'Rechercher',
    quickLanguage: 'Langue',
    agentStatusOnline: 'Actif & En écoute',
    agentStatusThinking: 'En réflexion',
    agentStatusExecuting: 'Exécution d’outils',
    agentStatusWaiting: 'Action requise',
    agentStatusConnecting: 'Connexion au démon',
    agentStatusOffline: 'Démon hors ligne',
    agentStatusError: 'Erreur de l’agent',
    agentStatusOnlineDesc: 'Prêt à traiter les commandes, outils et requêtes d’arrière-plan',
    agentStatusThinkingDesc: 'Formulation du raisonnement logique et du plan d’action',
    agentStatusExecutingDesc: 'Lancement des outils et diffusion de la réponse',
    daemonSupervised: 'Démon supervisé',
    gatewayStatus: 'État de la passerelle',
    activeModel: 'Modèle actif',
    quickActions: 'Actions rapides',
    launchChat: 'Lancer un nouveau chat',
    launchChatDesc: 'Ouvrir une session interactive avec autonomie totale des outils',
    diagnosticsAction: 'Diagnostics de la passerelle',
    diagnosticsActionDesc: 'Vérifier le pont IPC local et la santé du système',
    cronAction: 'Examiner les tâches Cron',
    cronActionDesc: 'Gérer les tâches périodiques et les déclencheurs',
    settingsAction: 'Personnaliser fournisseurs et thème',
    settingsActionDesc: 'Changer la palette, les clés LLM et la sécurité',
    recentSessions: 'Sessions récentes',
    scheduledCron: 'Tâches Cron en arrière-plan',
    noSessionsYet: 'Aucune session active',
    noJobsYet: 'Aucune tâche planifiée',
    configuredProviders: 'Fournisseurs configurés',
    addProvider: '+ Ajouter un fournisseur',
    editProvider: 'Modifier le fournisseur',
    active: 'Actif',
    use: 'Utiliser',
    edit: 'Modifier',
    delete: 'Supprimer',
    apiKey: 'Clé API',
    baseUrl: 'URL de base',
    defaultModel: 'Identifiant du modèle',
    testKey: 'Tester la clé',
    testingKey: 'Test en cours...',
    keyValid: 'Clé valide et fonctionnelle',
    keyInvalid: 'Échec de l’authentification',
    modelCatalog: 'Type de fournisseur',
    fontScale: 'Échelle de police du chat',
    fontScaleDesc: 'Ajuster la lisibilité des messages et des blocs de code',
    reasoningEffort: 'Niveau de raisonnement',
    reasoningEffortDesc: 'Budget alloué à la réflexion avant réponse',
    effortLow: 'Faible',
    effortMedium: 'Moyen',
    effortHigh: 'Élevé',
    autoApprove: 'Approbation auto des outils',
    autoApproveDesc: 'Ignorer la confirmation pour le terminal et les fichiers',
    appLock: 'Code PIN à 4 chiffres',
    appLockDesc: 'Exiger le code PIN avant d’afficher l’application',
    telegramBridge: 'Pont Bot Telegram',
    telegramBridgeDesc: 'Jeton de webhook pour relai mobile à distance',
    save: 'Enregistrer',
    cancel: 'Annuler',
    clearLogs: 'Effacer les journaux',
    restartDaemon: 'Redémarrer le démon',
    saveKeys: 'Enregistrer les identifiants',
    askHermes: 'Envoyez un message à Hermes ou collez vos instructions...',
    send: 'Envoyer',
    stop: 'Arrêter',
    thinkingProcess: 'Processus de réflexion',
    toolCalls: 'Exécution d’outils',
    emptyChatTitle: 'Agent Hermes Workspace',
    emptyChatDesc: 'Raisonnement autonome, exécution d’outils en ligne de commande et orchestration.',
    selectModel: 'Choisir le modèle',
    searchModels: 'Filtrer les modèles...',
    clearChat: 'Effacer l’historique',
    copy: 'Copier',
    fork: 'Dupliquer la session',
    exportChat: 'Exporter en Markdown',
    approve: 'Approuver & Exécuter',
    reject: 'Rejeter',
    scheduledJobsTitle: 'Tâches planifiées (Cron)',
    scheduledJobsDesc: 'Réveil autonome de l’agent selon les intervalles Cron',
    newJob: '+ Nouvelle tâche Cron',
    jobName: 'Nom de la tâche',
    cronSchedule: 'Planification Cron (ex: 0 9 * * *)',
    instructions: 'Instructions pour l’agent',
    enabled: 'Activé',
    actions: 'Actions',
    runNow: 'Exécuter maintenant',
    runsHistory: 'Historique des exécutions',
    lastRun: 'Dernière exécution',
  },

  de: {
    home: 'Übersicht',
    chat: 'Arbeitsbereich-Chat',
    jobs: 'Cron & Aufgaben',
    settings: 'Einstellungen',
    inference: 'Inferenz',
    daemonOps: 'Daemon & Betrieb',
    preferences: 'Präferenzen & Design',
    skillsMemory: 'Fähigkeiten & Speicher',
    themeTitle: 'Design & Farbpalette',
    themeSubtitle: 'Nur Desktop-Paletten. Der gewählte Modus wird darüber angewendet.',
    searchThemes: 'Themes durchsuchen...',
    light: 'Hell',
    dark: 'Dunkel',
    system: 'System',
    languageTitle: 'Sprache & Region',
    languageSubtitle: 'Wählen Sie Ihre Oberflächensprache. Hermes passt Text und Ausrichtung an.',
    searchLanguages: 'Sprachen suchen...',
    connected: 'Verbunden',
    offline: 'Getrennt',
    starting: 'Startet',
    approvalNeeded: 'Genehmigung erforderlich',
    inspector: 'Inspektor',
    deskTag: 'DESKTOP',
    newSession: 'Neue Sitzung',
    filterSessions: 'Sitzungen filtern...',
    search: 'Suchen',
    quickLanguage: 'Sprache',
    agentStatusOnline: 'Aktiv & Bereit',
    agentStatusThinking: 'Denkt nach',
    agentStatusExecuting: 'Führt Werkzeuge aus',
    agentStatusWaiting: 'Aktion erforderlich',
    agentStatusConnecting: 'Verbinde mit Daemon',
    agentStatusOffline: 'Daemon getrennt',
    agentStatusError: 'Agentenfehler',
    agentStatusOnlineDesc: 'Bereit für Befehle, Werkzeugaufrufe und Hintergrundanfragen',
    agentStatusThinkingDesc: 'Formuliert logische Schritte und Handlungsplan',
    agentStatusExecutingDesc: 'Führt Werkzeuge aus und streamt Ausgaben',
    daemonSupervised: 'Daemon überwacht',
    gatewayStatus: 'Gateway-Status',
    activeModel: 'Aktives Modell',
    quickActions: 'Schnellaktionen',
    launchChat: 'Neuen Chat starten',
    launchChatDesc: 'Interaktive Sitzung mit vollständiger Werkzeugautonomie öffnen',
    diagnosticsAction: 'Gateway-Diagnose prüfen',
    diagnosticsActionDesc: 'Lokale IPC-Bridge und Systemzustand testen',
    cronAction: 'Geplante Cron-Aufgaben prüfen',
    cronActionDesc: 'Regelmäßige Aufgaben und Trigger verwalten',
    settingsAction: 'Anbieter & Design anpassen',
    settingsActionDesc: 'Farbpalette, LLM-Endpunkte und Sicherheit ändern',
    recentSessions: 'Letzte Sitzungen',
    scheduledCron: 'Geplante Hintergrundaufgaben',
    noSessionsYet: 'Noch keine aktiven Sitzungen',
    noJobsYet: 'Keine geplanten Aufgaben',
    configuredProviders: 'Konfigurierte Modellanbieter',
    addProvider: '+ Anbieter hinzufügen',
    editProvider: 'Anbieter bearbeiten',
    active: 'Aktiv',
    use: 'Verwenden',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    apiKey: 'API-Schlüssel',
    baseUrl: 'Basis-URL',
    defaultModel: 'Standard-Modellkennung',
    testKey: 'Schlüssel testen',
    testingKey: 'Wird getestet...',
    keyValid: 'Schlüssel ist gültig',
    keyInvalid: 'Authentifizierung fehlgeschlagen',
    modelCatalog: 'Anbietertyp',
    fontScale: 'Chat-Schriftgröße',
    fontScaleDesc: 'Lesegröße für Nachrichten und Codeblöcke anpassen',
    reasoningEffort: 'Denkaufwand',
    reasoningEffortDesc: 'Budget für schrittweise logische Überlegung vor der Antwort',
    effortLow: 'Niedrig',
    effortMedium: 'Mittel',
    effortHigh: 'Hoch',
    autoApprove: 'Aktionen automatisch genehmigen',
    autoApproveDesc: 'Manuelle Bestätigung für Terminal und Dateien überspringen',
    appLock: '4-stellige App-PIN',
    appLockDesc: 'PIN vor Anzeige von Chats oder Einstellungen anfordern',
    telegramBridge: 'Telegram Bot Bridge',
    telegramBridgeDesc: 'Webhook-Token für mobile Fernsteuerung',
    save: 'Änderungen speichern',
    cancel: 'Abbrechen',
    clearLogs: 'Logs löschen',
    restartDaemon: 'Daemon neu starten',
    saveKeys: 'Zugangsdaten speichern',
    askHermes: 'Nachricht an Hermes senden oder Befehl einfügen...',
    send: 'Senden',
    stop: 'Ausführung stoppen',
    thinkingProcess: 'Denkprozess',
    toolCalls: 'Werkzeugausführung',
    emptyChatTitle: 'Hermes Workspace Agent',
    emptyChatDesc: 'Autonomes Nachdenken, Terminal-Werkzeuge und lokale Orchestrierung.',
    selectModel: 'Modell auswählen',
    searchModels: 'Modelle filtern...',
    clearChat: 'Verlauf leeren',
    copy: 'Kopieren',
    fork: 'Sitzung abzweigen',
    exportChat: 'Als Markdown exportieren',
    approve: 'Genehmigen & Ausführen',
    reject: 'Ablehnen',
    scheduledJobsTitle: 'Geplante Aufgaben (Cron)',
    scheduledJobsDesc: 'Automatisches Aufwecken des Agenten nach Cron-Intervall',
    newJob: '+ Neue Cron-Aufgabe',
    jobName: 'Aufgabenname',
    cronSchedule: 'Cron-Zeitplan (z.B. 0 9 * * *)',
    instructions: 'Anweisungen für den Agenten',
    enabled: 'Aktiviert',
    actions: 'Aktionen',
    runNow: 'Jetzt ausführen',
    runsHistory: 'Ausführungsverlauf',
    lastRun: 'Letzte Ausführung',
  },

  es: {
    home: 'Resumen',
    chat: 'Chat de Trabajo',
    jobs: 'Tareas y Cron',
    settings: 'Configuración',
    inference: 'Inferencia',
    daemonOps: 'Demonio y Operaciones',
    preferences: 'Preferencias y Apariencia',
    skillsMemory: 'Habilidades y Memoria',
    themeTitle: 'Tema y Paleta',
    themeSubtitle: 'Solo paletas de escritorio. El modo seleccionado se aplica encima.',
    searchThemes: 'Buscar tus temas...',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
    languageTitle: 'Idioma y Región',
    languageSubtitle: 'Selecciona el idioma de la interfaz. Hermes adaptará texto y orientación.',
    searchLanguages: 'Buscar idiomas...',
    connected: 'Conectado',
    offline: 'Desconectado',
    starting: 'Iniciando',
    approvalNeeded: 'Aprobación requerida',
    inspector: 'Inspector',
    deskTag: 'ESCRITORIO',
    newSession: 'Nueva Sesión',
    filterSessions: 'Filtrar sesiones...',
    search: 'Buscar',
    quickLanguage: 'Idioma',
    agentStatusOnline: 'Activo y Escuchando',
    agentStatusThinking: 'Razonando',
    agentStatusExecuting: 'Ejecutando Herramientas',
    agentStatusWaiting: 'Acción Requerida',
    agentStatusConnecting: 'Conectando al Demonio',
    agentStatusOffline: 'Demonio Desconectado',
    agentStatusError: 'Error del Agente',
    agentStatusOnlineDesc: 'Listo para procesar comandos, herramientas y solicitudes en segundo plano',
    agentStatusThinkingDesc: 'Formulando razonamiento paso a paso y plan de acción',
    agentStatusExecutingDesc: 'Ejecutando herramientas y transmitiendo la salida',
    daemonSupervised: 'Demonio Supervisado',
    gatewayStatus: 'Estado de la Pasarela',
    activeModel: 'Modelo Activo',
    quickActions: 'Acciones Rápidas',
    launchChat: 'Iniciar Nuevo Chat',
    launchChatDesc: 'Abrir sesión interactiva con autonomía total de herramientas',
    diagnosticsAction: 'Diagnósticos de la Pasarela',
    diagnosticsActionDesc: 'Verificar el puente IPC local y la salud del sistema',
    cronAction: 'Examinar Tareas Cron',
    cronActionDesc: 'Administrar tareas periódicas y activadores',
    settingsAction: 'Personalizar Proveedores y Apariencia',
    settingsActionDesc: 'Cambiar paleta de colores, claves LLM y seguridad',
    recentSessions: 'Sesiones Recientes',
    scheduledCron: 'Tareas Cron en Segundo Plano',
    noSessionsYet: 'Sin sesiones activas aún',
    noJobsYet: 'Sin tareas programadas',
    configuredProviders: 'Proveedores Configurados',
    addProvider: '+ Añadir Proveedor',
    editProvider: 'Editar Proveedor',
    active: 'Activo',
    use: 'Usar',
    edit: 'Editar',
    delete: 'Eliminar',
    apiKey: 'Clave API',
    baseUrl: 'URL Base',
    defaultModel: 'Identificador del Modelo',
    testKey: 'Probar Clave',
    testingKey: 'Probando...',
    keyValid: 'La clave es válida y responde',
    keyInvalid: 'Error de autenticación',
    modelCatalog: 'Tipo de Proveedor',
    fontScale: 'Escala de Fuente del Chat',
    fontScaleDesc: 'Ajustar legibilidad de mensajes y bloques de código',
    reasoningEffort: 'Esfuerzo de Razonamiento',
    reasoningEffortDesc: 'Presupuesto asignado a la cadena de pensamiento antes de responder',
    effortLow: 'Bajo',
    effortMedium: 'Medio',
    effortHigh: 'Alto',
    autoApprove: 'Auto-aprobar herramientas',
    autoApproveDesc: 'Omitir confirmación manual para terminal y archivos',
    appLock: 'PIN de Bloqueo de 4 Dígitos',
    appLockDesc: 'Requerir PIN antes de ver chats o ajustes',
    telegramBridge: 'Puente Bot de Telegram',
    telegramBridgeDesc: 'Token de webhook para control remoto desde el móvil',
    save: 'Guardar Cambios',
    cancel: 'Cancelar',
    clearLogs: 'Limpiar Registros',
    restartDaemon: 'Reiniciar Demonio',
    saveKeys: 'Guardar Credenciales',
    askHermes: 'Escribe a Hermes o pega instrucciones...',
    send: 'Enviar',
    stop: 'Detener Ejecución',
    thinkingProcess: 'Proceso de Razonamiento',
    toolCalls: 'Ejecución de Herramientas',
    emptyChatTitle: 'Agente Hermes Workspace',
    emptyChatDesc: 'Razonamiento autónomo, herramientas de terminal y orquestación local.',
    selectModel: 'Seleccionar Modelo',
    searchModels: 'Filtrar modelos...',
    clearChat: 'Borrar Historial',
    copy: 'Copiar',
    fork: 'Bifurcar Sesión',
    exportChat: 'Exportar a Markdown',
    approve: 'Aprobar y Ejecutar',
    reject: 'Rechazar',
    scheduledJobsTitle: 'Tareas Programadas (Cron)',
    scheduledJobsDesc: 'Activación autónoma del agente por intervalos Cron',
    newJob: '+ Nueva Tarea Cron',
    jobName: 'Nombre de la Tarea',
    cronSchedule: 'Programación Cron (ej: 0 9 * * *)',
    instructions: 'Instrucciones para el Agente',
    enabled: 'Habilitado',
    actions: 'Acciones',
    runNow: 'Ejecutar Ahora',
    runsHistory: 'Historial de Ejecución',
    lastRun: 'Última Ejecución',
  },
};

const warnedMissingKeys = new Set<string>();

const isDevBuild = (): boolean => {
  try {
    return (import.meta as any)?.env?.DEV === true;
  } catch {
    return false;
  }
};

export const getTranslation = (key: string, lang: string = 'en'): string => {
  const raw = (lang || 'en').toLowerCase();
  // Legacy alias: zh-hant was removed from LANGUAGES; map stored values to zh.
  const normLang = raw === 'zh-hant' || raw === 'zh_hant' ? 'zh' : raw;
  const missing =
    TRANSLATIONS[normLang]?.[key] === undefined &&
    TRANSLATIONS['en']?.[key] === undefined;
  if (missing && isDevBuild() && !warnedMissingKeys.has(key)) {
    warnedMissingKeys.add(key);
    console.warn(`[i18n] missing translation key: "${key}"`);
  }
  return TRANSLATIONS[normLang]?.[key] || TRANSLATIONS['en']?.[key] || key;
};

// BCP 47 locale tag per settings.language. Used for SpeechRecognition,
// toLocaleString dates, and any Intl API so UI locale follows the setting.
export const BCP47_LOCALES: Record<string, string> = {
  en: 'en-US',
  ar: 'ar-SA',
  zh: 'zh-CN',
  ja: 'ja-JP',
  ru: 'ru-RU',
  fr: 'fr-FR',
  de: 'de-DE',
  es: 'es-ES',
};

export const localeForLanguage = (lang: string = 'en'): string => {
  const raw = (lang || 'en').toLowerCase();
  const norm = raw === 'zh-hant' || raw === 'zh_hant' ? 'zh' : raw;
  return BCP47_LOCALES[norm] || 'en-US';
};

export const speechLocaleForLanguage = (lang: string = 'en'): string =>
  localeForLanguage(lang);

// Locale-aware date/time formatting. Replaces manual ISO munging and
// bare toLocaleString() calls that ignored settings.language.
export const formatDateTime = (value: number | string | Date, lang: string = 'en'): string => {
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return '';
  return d.toLocaleString(localeForLanguage(lang));
};

// Localized relative time for homeAgo-style labels. {n} is substituted
// with the computed amount so keys stay interpolation-free for t().
export const formatHomeAgo = (epochMs: number | null | undefined, lang: string = 'en'): string => {
  const tr = (key: string): string => getTranslation(key, lang);
  if (!epochMs) return tr('timeNever');
  const s = Math.max(0, Math.floor((Date.now() - epochMs) / 1000));
  if (s < 60) return tr('timeJustNow');
  const m = Math.floor(s / 60);
  if (m < 60) return tr('timeMinAgo').replace('{n}', String(m));
  const h = Math.floor(m / 60);
  if (h < 24) return tr('timeHourAgo').replace('{n}', String(h));
  return tr('timeDayAgo').replace('{n}', String(Math.floor(h / 24)));
};
