export const PROVIDER_OPTIONS: Array<[string, string]> = [
  ['openrouter', 'OpenRouter'],
  ['mixture-of-agents', 'Mixture of Agents'],
  ['deepseek', 'DeepSeek'],
  ['opencode-go', 'OpenCode Go'],
  ['opencode-zen', 'OpenCode Zen'],
  ['openai-api', 'OpenAI API'],
  ['anthropic', 'Anthropic'],
  ['gemini', 'Google AI Studio'],
  ['xai', 'xAI'],
  ['kimi-coding', 'Kimi / Moonshot'],
  ['kimi-coding-cn', 'Kimi / Moonshot (China)'],
  ['zai', 'Z.AI / GLM'],
  ['minimax', 'MiniMax'],
  ['minimax-cn', 'MiniMax (China)'],
  ['alibaba', 'Qwen Cloud'],
  ['alibaba-coding-plan', 'Alibaba Cloud (Coding Plan)'],
  ['nvidia', 'NVIDIA NIM'],
  ['ai-gateway', 'Vercel AI Gateway'],
  ['kilocode', 'Kilo Code'],
  ['huggingface', 'Hugging Face'],
  ['xiaomi', 'Xiaomi MiMo'],
  ['tencent-tokenhub', 'Tencent TokenHub'],
  ['tencent-tokenplan', 'Tencent TokenPlan'],
  ['ollama-cloud', 'Ollama Cloud'],
  ['lmstudio', 'LM Studio'],
  ['copilot', 'GitHub Copilot'],
  ['stepfun', 'StepFun Step Plan'],
  ['arcee', 'Arcee AI'],
  ['gmi', 'GMI Cloud'],
  ['actual', 'Actual Computer'],
  ['azure-foundry', 'Azure Foundry'],
];

export const PROVIDER_ALIASES: Record<string, string> = {
  glm: 'zai',
  'z-ai': 'zai',
  'z.ai': 'zai',
  zhipu: 'zai',
  google: 'gemini',
  'google-gemini': 'gemini',
  'google-ai-studio': 'gemini',
  'x-ai': 'xai',
  'x.ai': 'xai',
  grok: 'xai',
  kimi: 'kimi-coding',
  'kimi-for-coding': 'kimi-coding',
  moonshot: 'kimi-coding',
  'kimi-cn': 'kimi-coding-cn',
  'moonshot-cn': 'kimi-coding-cn',
  step: 'stepfun',
  'stepfun-coding-plan': 'stepfun',
  'arcee-ai': 'arcee',
  arceeai: 'arcee',
  'gmi-cloud': 'gmi',
  gmicloud: 'gmi',
  'actual-computer': 'actual',
  actualcomputer: 'actual',
  aci: 'actual',
  'minimax-china': 'minimax-cn',
  minimax_cn: 'minimax-cn',
  alibaba_coding: 'alibaba-coding-plan',
  'alibaba-coding': 'alibaba-coding-plan',
  alibaba_coding_plan: 'alibaba-coding-plan',
  claude: 'anthropic',
  'claude-code': 'anthropic',
  github: 'copilot',
  'github-copilot': 'copilot',
  'github-models': 'copilot',
  'github-model': 'copilot',
  aigateway: 'ai-gateway',
  vercel: 'ai-gateway',
  'vercel-ai-gateway': 'ai-gateway',
  opencode: 'opencode-zen',
  zen: 'opencode-zen',
  hf: 'huggingface',
  'hugging-face': 'huggingface',
  'huggingface-hub': 'huggingface',
  mimo: 'xiaomi',
  'xiaomi-mimo': 'xiaomi',
  tencent: 'tencent-tokenhub',
  tokenhub: 'tencent-tokenhub',
  'tencent-cloud': 'tencent-tokenhub',
  tencentmaas: 'tencent-tokenhub',
  tokenplan: 'tencent-tokenplan',
  'tencent-lkeap': 'tencent-tokenplan',
  go: 'opencode-go',
  'opencode-go-sub': 'opencode-go',
  kilo: 'kilocode',
  'kilo-code': 'kilocode',
  'kilo-gateway': 'kilocode',
  'lm-studio': 'lmstudio',
  lm_studio: 'lmstudio',
};

export const KNOWN_PROVIDERS = new Set(PROVIDER_OPTIONS.map(([id]) => id));

export function normProvider(p: string): string {
  const slug = p.trim().toLowerCase().replace(/\s+/g, '-');
  return PROVIDER_ALIASES[slug] || slug;
}

export function keysValid(provider: string, key: string, baseUrl: string): boolean {
  const p = normProvider(provider).trim() || 'deepseek';
  if (KEYLESS_PROVIDERS.has(p)) return true;
  if (!key.trim()) return false;
  return KNOWN_PROVIDERS.has(p) || baseUrl.trim().length > 0;
}

export const KEYLESS_PROVIDERS = new Set(['lmstudio', 'ollama-cloud']);

export const DEFAULT_MODELS: Record<string, string[]> = {
  openrouter: [
    'anthropic/claude-fable-5.1',
    'anthropic/claude-fable-5',
    'anthropic/claude-opus-5.5',
    'anthropic/claude-opus-5',
    'anthropic/claude-opus-4.8',
    'anthropic/claude-sonnet-5',
    'anthropic/claude-3-7-sonnet',
    'anthropic/claude-3-5-sonnet',
    'deepseek/deepseek-r1',
    'deepseek/deepseek-chat',
    'openai/gpt-4o',
    'openai/gpt-4o-mini',
    'openai/o3-mini',
    'google/gemini-2.5-pro',
    'meta-llama/llama-3.3-70b-instruct',
    'qwen/qwen-2.5-72b-instruct',
  ],
  'mixture-of-agents': [
    'moa/hermes-swarm-ultra',
    'moa/deepseek-claude-hybrid',
    'moa/reasoning-ensemble-v2',
  ],
  deepseek: ['deepseek/deepseek-chat', 'deepseek/deepseek-reasoner'],
  'opencode-go': ['opencode-go/default', 'opencode-go/auto'],
  'opencode-zen': ['opencode-zen/default', 'opencode-zen/auto'],
  xiaomi: ['mimo-v2-flash', 'mimo-v2-thinking-flash'],
  'tencent-tokenhub': ['tokenhub-default', 'tokenhub-plus'],
  'tencent-tokenplan': ['tokenplan-default', 'tokenplan-plus'],
  gemini: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-2.0-flash-exp'],
  anthropic: ['claude-3-7-sonnet', 'claude-3-5-sonnet', 'claude-3-5-haiku'],
  'openai-api': ['gpt-4o', 'gpt-4o-mini', 'o3-mini', 'o1'],
  xai: ['grok-2-latest', 'grok-beta'],
  'kimi-coding': ['moonshot-v1-auto', 'moonshot-v1-8k', 'moonshot-v1-32k'],
  'kimi-coding-cn': ['moonshot-v1-auto', 'moonshot-v1-8k'],
  zai: ['glm-4-plus', 'glm-4-air', 'glm-4-flash'],
  minimax: ['MiniMax-Text-01', 'abab6.5s-chat'],
  'minimax-cn': ['MiniMax-Text-01', 'abab6.5s-chat'],
  alibaba: ['qwen-max', 'qwen-plus', 'qwen-turbo'],
  'alibaba-coding-plan': ['qwen-coder-plus', 'qwen-coder-turbo'],
  nvidia: ['meta/llama-3.3-70b-instruct', 'deepseek-ai/deepseek-r1'],
  'ai-gateway': ['openai/gpt-4o', 'anthropic/claude-3-5-sonnet'],
  kilocode: ['kilo-coder-v1'],
  huggingface: ['meta-llama/Llama-3.3-70B-Instruct', 'mistralai/Mistral-Small-24B-Instruct-2501'],
  'ollama-cloud': ['llama3.3:70b', 'qwen2.5-coder:32b', 'deepseek-r1:32b'],
  lmstudio: ['local-model'],
  copilot: ['gpt-4o', 'claude-3.5-sonnet'],
  stepfun: ['step-2-16k', 'step-1-8k'],
  arcee: ['arcee-super', 'arcee-spark'],
  gmi: ['meta/llama-3.1-405b-instruct'],
  actual: ['actual-default-model'],
  'azure-foundry': ['azure-gpt-4o', 'azure-o1'],
};
